## 1.0  Reading CSV File

We will use pandas, a package in python that allows data to be represented in easily manipulated strcutures.  One of the most useful is a dataframe, where data are arranged in rows (as observations) and columns (variables), similar to what we are used to in the EXCEL spreasheet.

Below are the commands for reading the CSV file.

Unfortuately, the error message indicates that the data cannot be read as the file is not in the default 'utf-8' format.

In [8]:
import pandas as pd
stock = pd.read_csv("STI_Index.csv")
stock

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 4: invalid start byte

We use the function from the chardet module to determine how the file we want to read in is encoded.  It turns out toe be 'ISO-8859-1'

In [9]:
import chardet
fh = open("STI_Index.csv", "rb").read()
chardet.detect(fh)

{'confidence': 0.73, 'encoding': 'ISO-8859-1', 'language': ''}

Now all we have to do is to include encoding as one of the arguments that we pass to the pd.read_csv() method as illustrated below. Note that we end up with a neatly arranged table.  The python terminology for the table created is a DataFrame or more specifically a pandas DataFrame

In [14]:
import pandas as pd
stock = pd.read_csv("STI_Index.csv", encoding = "ISO-8859-1")
stock

,Counter_Name,Code,Last,Chg,PercentChange,Vol,B Vol,Buy,Sell,S Vol,High,Low,Value,Sector
0,OCBC Bank,O39,11.68,-,-,"2,824.50",21.2,11.67,11.680,15.7,11.760,11.610,"32,993,891",FIN
1,Ascendas Reit,A17U,2.63,0.01,0.382,"2,382.50",425.5,2.62,2.630,198.6,2.640,2.610,"6,245,997.50",PROP
2,CapitaLand,C31,3.18,-0.02,-0.625,"4,501.20",569,3.18,3.190,722.7,3.210,3.170,"14,339,453",PROP
3,CapitaMall Trust,C38U,2.02,-0.02,-0.98,"5,270.20","3,126.30",2.02,2.030,"1,173.50",2.040,2.010,"10,677,863.60",PROP
4,CityDev,C09,11.02,-0.07,-0.631,958.7,10,11.02,11.030,9.2,11.060,10.950,"10,562,490",PROP
5,ComfortDelGro,C52,2.3,0.04,1.77,"4,902.90",286.3,2.30,2.310,654.3,2.320,2.250,"11,225,389",TSC
6,DBS,D05,26.83,-0.11,-0.408,"2,993.60",4.9,26.83,26.840,3.8,27.200,26.800,"80,860,990",FIN
7,Genting Sing,G13,1.22,-,-,"19,180.20","3,408.10",1.21,1.220,"3,008.40",1.240,1.210,"23,447,047",Hotels
8,Golden Agri-Res,E5H,0.31,-0.005,-1.587,"2,760.70","7,885.80",0.31,0.315,"8,226.80",0.315,0.310,"866,624.50",AGR
9,HongkongLand USD,H78,7.17,-0.01,-0.139,411.7,1,7.17,7.180,10.2,7.190,7.150,"2,951,162",PROP
10,HPH Trust USD,NS8U,0.28,-,-,"17,943.60","7,987.20",0.28,0.285,"7,876.50",0.285,0.275,"5,028,804.50",TSC
11,Jardine C&C,C07,32.18,0.06,0.187,76.2,1.2,32.18,32.190,1,32.480,32.120,"2,462,513",COM
12,JMH USD,J36,63.02,0.01,0.016,76.5,0.2,62.87,63.020,0.3,63.020,62.700,"4,810,851",COM
13,JSH USD,J37,36.39,-0.14,-0.383,86,0.3,36.38,36.440,0.3,36.940,36.360,"3,136,015",COM
14,Keppel Corp,BN4,7.18,0.09,1.269,"3,188.30",71.8,7.17,7.180,76.3,7.240,7.130,"22,923,951",Multi
15,CapitaCom Trust,C61U,1.64,-0.02,-1.205,"7,647.90","3,722.90",1.63,1.640,85,1.660,1.630,"12,568,100",PROP
16,SATS,S58,4.95,-0.01,-0.202,765.5,71.5,4.94,4.950,32.9,4.960,4.920,"3,782,204",SERV
17,Sembcorp Ind,U96,2.79,0.03,1.087,"2,939",225.3,2.78,2.790,94.2,2.830,2.770,"8,244,786",Multi
18,SGX,S68,7.22,0.09,1.262,964.6,28,7.21,7.220,15.3,7.230,7.130,"6,948,203",FIN
19,SIA,C6L,10.9,0.03,0.276,433.1,11.3,10.89,10.900,13.5,10.970,10.860,"4,726,874",TSC
20,SingTel,Z74,3.11,-0.01,-0.321,"11,943.10","2,940.20",3.11,3.120,"2,389.80",3.120,3.100,"37,194,598",TSC
21,SPH,T39,2.61,-,-,"1,080.10",165.2,2.60,2.610,378.7,2.620,2.590,"2,809,424",MFG
22,ST Engineering,S63,3.32,-0.03,-0.896,"2,455",167.8,3.31,3.320,219.7,3.370,3.310,"8,198,752",Multi
23,StarHub,CC3,1.71,-0.02,-1.156,"6,553.80",98.1,1.70,1.710,230.3,1.750,1.670,"11,191,367",TSC
24,ThaiBev,Y92,0.745,-,-,"7,415.90","2,413.70",0.74,0.745,"1,655.20",0.750,0.740,"5,522,935.40",MFG
25,UOB,U11,26.71,0.11,0.414,"1,305.30",1.9,26.70,26.710,7,26.790,26.460,"34,787,502",FIN
26,UOL,U14,7.62,0.09,1.195,683.6,9.4,7.62,7.630,3.1,7.670,7.500,"5,204,928",PROP
27,Venture,V03,17.69,0.04,0.227,"1,084.70",1.9,17.68,17.690,0.5,17.880,17.510,"19,224,610",MFG
28,Wilmar Intl,F34,3.06,-,-,"3,279.90",191.3,3.06,3.070,161.1,3.100,3.050,"10,100,631",MFG
29,YZJ Shipbldg SGD,BS6,0.92,-0.015,-1.604,"17,785.30","3,378.30",0.92,0.925,"2,099.10",0.940,0.920,"16,505,420",MFG
30,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
type(stock)

pandas.core.frame.DataFrame

We look at the type of data that are in each column.  object are strings whilst float are numeric.
Note that even though we see "Value" as numeric in the csv file, it is read in as strings in this case.  
This is because of the commas (',') in the thousand places of the units.

We want to add up the "Value" of all the 30 stocks.  What should we do?

In [2]:
stock.dtypes

Counter_Name      object
Code              object
Last              object
Chg               object
PercentChange     object
Vol               object
B Vol             object
Buy              float64
Sell             float64
S Vol             object
High             float64
Low              float64
Value             object
Sector            object
dtype: object

The .shape method indicates that the stock DataFrame has 31 rows and 14 columns.

In [3]:
stock.shape

(31, 14)

We can access specific rows by using the iloc[] method.  Below we look at the second row.

iloc[] extracts the index of the rows (as opposed to columns).  So iloc[1] is the second row.

In [15]:
stock.iloc[1]

Counter_Name     Ascendas Reit
Code                      A17U
Last                      2.63
Chg                       0.01
PercentChange            0.382
Vol                   2,382.50
B Vol                    425.5
Buy                       2.62
Sell                      2.63
S Vol                    198.6
High                      2.64
Low                       2.61
Value             6,245,997.50
Sector                    PROP
Name: 1, dtype: object

The last row contains no data - so we wish to get rid of it by creating a new DataFrame (does not matter that it is the same name) without the last row

In [15]:
print(len(stock)) # before removing of NaN row: 31
stock = stock[stock['Counter_Name'].notnull()]
print(len(stock)) # After removing of NaN row: 30
stock

31
30

,Counter_Name,Code,Last,Chg,PercentChange,Vol,B Vol,Buy,Sell,S Vol,High,Low,Value,Sector
0,OCBC Bank,O39,11.68,-,-,"2,824.50",21.2,11.67,11.680,15.7,11.760,11.610,"32,993,891",FIN
1,Ascendas Reit,A17U,2.63,0.01,0.382,"2,382.50",425.5,2.62,2.630,198.6,2.640,2.610,"6,245,997.50",PROP
2,CapitaLand,C31,3.18,-0.02,-0.625,"4,501.20",569,3.18,3.190,722.7,3.210,3.170,"14,339,453",PROP
3,CapitaMall Trust,C38U,2.02,-0.02,-0.98,"5,270.20","3,126.30",2.02,2.030,"1,173.50",2.040,2.010,"10,677,863.60",PROP
4,CityDev,C09,11.02,-0.07,-0.631,958.7,10,11.02,11.030,9.2,11.060,10.950,"10,562,490",PROP
5,ComfortDelGro,C52,2.3,0.04,1.77,"4,902.90",286.3,2.30,2.310,654.3,2.320,2.250,"11,225,389",TSC
6,DBS,D05,26.83,-0.11,-0.408,"2,993.60",4.9,26.83,26.840,3.8,27.200,26.800,"80,860,990",FIN
7,Genting Sing,G13,1.22,-,-,"19,180.20","3,408.10",1.21,1.220,"3,008.40",1.240,1.210,"23,447,047",Hotels
8,Golden Agri-Res,E5H,0.31,-0.005,-1.587,"2,760.70","7,885.80",0.31,0.315,"8,226.80",0.315,0.310,"866,624.50",AGR
9,HongkongLand USD,H78,7.17,-0.01,-0.139,411.7,1,7.17,7.180,10.2,7.190,7.150,"2,951,162",PROP
10,HPH Trust USD,NS8U,0.28,-,-,"17,943.60","7,987.20",0.28,0.285,"7,876.50",0.285,0.275,"5,028,804.50",TSC
11,Jardine C&C,C07,32.18,0.06,0.187,76.2,1.2,32.18,32.190,1,32.480,32.120,"2,462,513",COM
12,JMH USD,J36,63.02,0.01,0.016,76.5,0.2,62.87,63.020,0.3,63.020,62.700,"4,810,851",COM
13,JSH USD,J37,36.39,-0.14,-0.383,86,0.3,36.38,36.440,0.3,36.940,36.360,"3,136,015",COM
14,Keppel Corp,BN4,7.18,0.09,1.269,"3,188.30",71.8,7.17,7.180,76.3,7.240,7.130,"22,923,951",Multi
15,CapitaCom Trust,C61U,1.64,-0.02,-1.205,"7,647.90","3,722.90",1.63,1.640,85,1.660,1.630,"12,568,100",PROP
16,SATS,S58,4.95,-0.01,-0.202,765.5,71.5,4.94,4.950,32.9,4.960,4.920,"3,782,204",SERV
17,Sembcorp Ind,U96,2.79,0.03,1.087,"2,939",225.3,2.78,2.790,94.2,2.830,2.770,"8,244,786",Multi
18,SGX,S68,7.22,0.09,1.262,964.6,28,7.21,7.220,15.3,7.230,7.130,"6,948,203",FIN
19,SIA,C6L,10.9,0.03,0.276,433.1,11.3,10.89,10.900,13.5,10.970,10.860,"4,726,874",TSC
20,SingTel,Z74,3.11,-0.01,-0.321,"11,943.10","2,940.20",3.11,3.120,"2,389.80",3.120,3.100,"37,194,598",TSC
21,SPH,T39,2.61,-,-,"1,080.10",165.2,2.60,2.610,378.7,2.620,2.590,"2,809,424",MFG
22,ST Engineering,S63,3.32,-0.03,-0.896,"2,455",167.8,3.31,3.320,219.7,3.370,3.310,"8,198,752",Multi
23,StarHub,CC3,1.71,-0.02,-1.156,"6,553.80",98.1,1.70,1.710,230.3,1.750,1.670,"11,191,367",TSC
24,ThaiBev,Y92,0.745,-,-,"7,415.90","2,413.70",0.74,0.745,"1,655.20",0.750,0.740,"5,522,935.40",MFG
25,UOB,U11,26.71,0.11,0.414,"1,305.30",1.9,26.70,26.710,7,26.790,26.460,"34,787,502",FIN
26,UOL,U14,7.62,0.09,1.195,683.6,9.4,7.62,7.630,3.1,7.670,7.500,"5,204,928",PROP
27,Venture,V03,17.69,0.04,0.227,"1,084.70",1.9,17.68,17.690,0.5,17.880,17.510,"19,224,610",MFG
28,Wilmar Intl,F34,3.06,-,-,"3,279.90",191.3,3.06,3.070,161.1,3.100,3.050,"10,100,631",MFG
29,YZJ Shipbldg SGD,BS6,0.92,-0.015,-1.604,"17,785.30","3,378.30",0.92,0.925,"2,099.10",0.940,0.920,"16,505,420",MFG

In [16]:
stock['Value']

KeyError: 'Value'

After a number of tries at accessing the columns and getting KeyError: 'Value' above, I decide to investigate how the column headings are actually represented.  The command stock.columns prints out the names of the column headings.  Surprise - there are trailing white spaces in the last twelve names.  This is causing the error as I had asked for "Value" which does not have the spaces.

In [21]:
stock.columns

Index(['Counter_Name', 'Code', 'Last ', 'Chg ', 'PercentChange', 'Vol ',
       'B Vol ', 'Buy ', 'Sell ', 'S Vol ', 'High ', 'Low ', 'Value ',
       'Sector '],
      dtype='object')

Rather than try to work with the white spaces, we run a command to get rid of the trailing spaces as below.

Now we get the results we want.

In [18]:
stock.columns = stock.columns.str.strip()
stock.columns

Index(['Counter_Name', 'Code', 'Last', 'Chg', 'PercentChange', 'Vol', 'B Vol',
       'Buy', 'Sell', 'S Vol', 'High', 'Low', 'Value', 'Sector'],
      dtype='object')

In [23]:
stock['Value']

0        32,993,891
1      6,245,997.50
2        14,339,453
3     10,677,863.60
4        10,562,490
5        11,225,389
6        80,860,990
7        23,447,047
8        866,624.50
9         2,951,162
10     5,028,804.50
11        2,462,513
12        4,810,851
13        3,136,015
14       22,923,951
15       12,568,100
16        3,782,204
17        8,244,786
18        6,948,203
19        4,726,874
20       37,194,598
21        2,809,424
22        8,198,752
23       11,191,367
24     5,522,935.40
25       34,787,502
26        5,204,928
27       19,224,610
28       10,100,631
29       16,505,420
Name: Value, dtype: object

Note that 'Values' is not numeric and cannot be summed.

In [24]:
sum(stock['Value'])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

We try to use the same function as in the previous lesson on reading text file to convert the strings to float.  However, it does not work this time as we are trying to use a single command to change for the entire series.

In [25]:
stock['ValueFloat']=float(stock['Value'].replace(',',''))

TypeError: cannot convert the series to <class 'float'>

We use list comprehension to replace the commas(which is similar to a loop except that it is much neater)

In [19]:
stock['ValueFloat']=[x.replace(',','') for x in stock['Value']]

C:\Users\isep\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [20]:
stock['ValueFloat']

0        32993891
1      6245997.50
2        14339453
3     10677863.60
4        10562490
5        11225389
6        80860990
7        23447047
8       866624.50
9         2951162
10     5028804.50
11        2462513
12        4810851
13        3136015
14       22923951
15       12568100
16        3782204
17        8244786
18        6948203
19        4726874
20       37194598
21        2809424
22        8198752
23       11191367
24     5522935.40
25       34787502
26        5204928
27       19224610
28       10100631
29       16505420
Name: ValueFloat, dtype: object

We then change the 'ValueFloat' which is string to float using list comprehension

In [27]:
stock['ValueFloat'] = [float(x) for x in stock['ValueFloat']]
stock['ValueFloat']

C:\Users\isep\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

0     32993891.0
1      6245997.5
2     14339453.0
3     10677863.6
4     10562490.0
5     11225389.0
6     80860990.0
7     23447047.0
8       866624.5
9      2951162.0
10     5028804.5
11     2462513.0
12     4810851.0
13     3136015.0
14    22923951.0
15    12568100.0
16     3782204.0
17     8244786.0
18     6948203.0
19     4726874.0
20    37194598.0
21     2809424.0
22     8198752.0
23    11191367.0
24     5522935.4
25    34787502.0
26     5204928.0
27    19224610.0
28    10100631.0
29    16505420.0
Name: ValueFloat, dtype: float64

We can finally sum up the market value.  With the appropriate format included.

In [28]:
print('{} {:0,.0f}'.format('$',sum(stock['ValueFloat'])))

$ 419,543,376

## 2.0  Writing CSV File

It is a simple procedure to use the function .to_csv to write the whole dataframe to a csv file as illustrated below.  We put the "index=False" to prevent the printing of indices (1,2,3 . . .) in the first column of the csv file.

In [29]:
stock.to_csv('MarketValue.csv', index=False)

If we want to only write out specific columns, you must specify them using the columns parameters.

In [33]:
stock.to_csv('MarketValueSelected.csv', index=False, columns = ["Counter_Name", "ValueFloat"])

We can select to write selected lines individually into the csv file instead of writing the whole dataframe.

Note that the end of each line has the format statement '\n'.

This will make sure that the next line of data is written on a new line.

In [35]:
with open('MarketValueLine.csv',"w") as fileout:
    fileout.write(','.join(map(str,stock.columns))+'\n')
    for i in range(len(stock)):
        fileout.write(','.join(map(str,stock.iloc[i]))+'\n')

In [36]:
import csv
writer = csv.writer(open('MarketValueCSVWriter.csv', 'w'))

writer.writerows(str(stock) +'\n')
del writer