## 1.0 Reading EXCEL File

The easiest way to get the file you read in in a format that facilitates data manipulation is to do so in a dataframe format.  So we read in the EXCEL file we have on hand as a dataframe.

After using the command to read in the data using the command pd.ExcelFile, we note that all the sheets in the Excel files are read.  They can be seen by using the command excelFile.sheet_names

In [1]:
import pandas as pd
excelFile = pd.ExcelFile('STI_Index.xlsx')
excelFile.sheet_names

['STI', 'DJIA']

In [2]:
type(excelFile)

pandas.io.excel.ExcelFile

We load the sheet we want to work with in a dataframe by using the command .parse and assigning the output to an object named stock.  Notice that missing data are given the default value of NaN when read in.

In [3]:
stock = excelFile.parse('STI')
stock

,Counter Name,SIP,Code,Rmk,Last,Chg,%,Vol,B Vol,Buy,Sell,S Vol,High,Low,Value,Sector
0,OCBC Bank,NaN,O39,NaN,11.680,-,-,2824.5,21.2,11.67,11.680,15.7,11.760,11.610,32993891.0,FIN
1,Ascendas Reit,NaN,A17U,NaN,2.630,0.01,0.382,2382.5,425.5,2.62,2.630,198.6,2.640,2.610,6245997.5,PROP
2,CapitaLand,NaN,C31,NaN,3.180,-0.02,-0.625,4501.2,569.0,3.18,3.190,722.7,3.210,3.170,14339453.0,PROP
3,CapitaMall Trust,NaN,C38U,NaN,2.020,-0.02,-0.98,5270.2,3126.3,2.02,2.030,1173.5,2.040,2.010,10677863.6,PROP
4,CityDev,NaN,C09,NaN,11.020,-0.07,-0.631,958.7,10.0,11.02,11.030,9.2,11.060,10.950,10562490.0,PROP
5,ComfortDelGro,NaN,C52,NaN,2.300,0.04,1.77,4902.9,286.3,2.30,2.310,654.3,2.320,2.250,11225389.0,TSC
6,DBS,NaN,D05,NaN,26.830,-0.11,-0.408,2993.6,4.9,26.83,26.840,3.8,27.200,26.800,80860990.0,FIN
7,Genting Sing,NaN,G13,NaN,1.220,-,-,19180.2,3408.1,1.21,1.220,3008.4,1.240,1.210,23447047.0,Hotels
8,Golden Agri-Res,NaN,E5H,NaN,0.310,-0.005,-1.587,2760.7,7885.8,0.31,0.315,8226.8,0.315,0.310,866624.5,AGR
9,HongkongLand USD,NaN,H78,NaN,7.170,-0.01,-0.139,411.7,1.0,7.17,7.180,10.2,7.190,7.150,2951162.0,PROP
10,HPH Trust USD,NaN,NS8U,NaN,0.280,-,-,17943.6,7987.2,0.28,0.285,7876.5,0.285,0.275,5028804.5,TSC
11,Jardine C&C,NaN,C07,NaN,32.180,0.06,0.187,76.2,1.2,32.18,32.190,1.0,32.480,32.120,2462513.0,COM
12,JMH USD,NaN,J36,NaN,63.020,0.01,0.016,76.5,0.2,62.87,63.020,0.3,63.020,62.700,4810851.0,COM
13,JSH USD,NaN,J37,NaN,36.390,-0.14,-0.383,86.0,0.3,36.38,36.440,0.3,36.940,36.360,3136015.0,COM
14,Keppel Corp,NaN,BN4,NaN,7.180,0.09,1.269,3188.3,71.8,7.17,7.180,76.3,7.240,7.130,22923951.0,Multi
15,CapitaCom Trust,NaN,C61U,NaN,1.640,-0.02,-1.205,7647.9,3722.9,1.63,1.640,85.0,1.660,1.630,12568100.0,PROP
16,SATS,NaN,S58,CD,4.950,-0.01,-0.202,765.5,71.5,4.94,4.950,32.9,4.960,4.920,3782204.0,SERV
17,Sembcorp Ind,NaN,U96,NaN,2.790,0.03,1.087,2939.0,225.3,2.78,2.790,94.2,2.830,2.770,8244786.0,Multi
18,SGX,NaN,S68,NaN,7.220,0.09,1.262,964.6,28.0,7.21,7.220,15.3,7.230,7.130,6948203.0,FIN
19,SIA,NaN,C6L,CD,10.900,0.03,0.276,433.1,11.3,10.89,10.900,13.5,10.970,10.860,4726874.0,TSC
20,SingTel,NaN,Z74,CD,3.110,-0.01,-0.321,11943.1,2940.2,3.11,3.120,2389.8,3.120,3.100,37194598.0,TSC
21,SPH,NaN,T39,NaN,2.610,-,-,1080.1,165.2,2.60,2.610,378.7,2.620,2.590,2809424.0,MFG
22,ST Engineering,NaN,S63,NaN,3.320,-0.03,-0.896,2455.0,167.8,3.31,3.320,219.7,3.370,3.310,8198752.0,Multi
23,StarHub,NaN,CC3,NaN,1.710,-0.02,-1.156,6553.8,98.1,1.70,1.710,230.3,1.750,1.670,11191367.0,TSC
24,ThaiBev,NaN,Y92,NaN,0.745,-,-,7415.9,2413.7,0.74,0.745,1655.2,0.750,0.740,5522935.4,MFG
25,UOB,NaN,U11,NaN,26.710,0.11,0.414,1305.3,1.9,26.70,26.710,7.0,26.790,26.460,34787502.0,FIN
26,UOL,NaN,U14,NaN,7.620,0.09,1.195,683.6,9.4,7.62,7.630,3.1,7.670,7.500,5204928.0,PROP
27,Venture,NaN,V03,NaN,17.690,0.04,0.227,1084.7,1.9,17.68,17.690,0.5,17.880,17.510,19224610.0,MFG
28,Wilmar Intl,NaN,F34,NaN,3.060,-,-,3279.9,191.3,3.06,3.070,161.1,3.100,3.050,10100631.0,MFG
29,YZJ Shipbldg SGD,NaN,BS6,NaN,0.920,-0.015,-1.604,17785.3,3378.3,0.92,0.925,2099.1,0.940,0.920,16505420.0,MFG

Let's look at the datatypes and how the column names are represented so that we can do some housekeeping before working on the data.

Note that unlike the case of reading in the text and CSV files when the 'Value' was read in as object (string), in this case, 'Value' is read in as float64(numeric).

In [4]:
stock.dtypes

Counter Name     object
SIP             float64
Code             object
Rmk              object
Last            float64
Chg              object
%                object
Vol             float64
B Vol           float64
Buy             float64
Sell            float64
S Vol           float64
High            float64
Low             float64
Value           float64
Sector           object
dtype: object

In [5]:
stock.columns

Index(['Counter Name', 'SIP', 'Code', 'Rmk ', 'Last ', 'Chg ', '% ', 'Vol ',
       'B Vol ', 'Buy ', 'Sell ', 'S Vol ', 'High ', 'Low ', 'Value ',
       'Sector '],
      dtype='object')

We note some of the column headings are read in with trailing white spaces.  These will cause problems later on when we use the column names in our data manipulation.

We remove the trailing blanks.

In [6]:
stock.columns = stock.columns.str.strip()
stock.columns

Index(['Counter Name', 'SIP', 'Code', 'Rmk', 'Last', 'Chg', '%', 'Vol',
       'B Vol', 'Buy', 'Sell', 'S Vol', 'High', 'Low', 'Value', 'Sector'],
      dtype='object')

Since the 'Value' is already in numeric format, we can take the sum of the values.

In [7]:
print('{} {:0,.0f}'.format('$',sum(stock['Value'])))

$ 419,543,376

## 2.0 Writing EXCEL File

To write the data to a file, we must first open and define the filename that you want to use.  This is done with the pd.ExcelWriter command.  This information is saved in the object we call writer.

We then save the dataframe named stock, using the .to_excel command, and passing the file object writer as an argument and identifying the name of the sheet in EXCEL to put the data in.

In [11]:
writer = pd.ExcelWriter('MarketValue.xlsx')
stock.to_excel(writer, 'Sheet1')
writer.save()

If you do not wish to print the first column of indices, just include the term index=False in the .to_excel command

In [12]:
writer = pd.ExcelWriter('MarketValueNoIndex.xlsx')
stock.to_excel(writer, 'STI', index=False)
writer.save()

It is possible to print selected columns by inserting the parameter "columns = " in the to_excel command

In [13]:
header = ['Counter Name', 'Vol', 'Value']
writer = pd.ExcelWriter('MarketValueSelected.xlsx')
stock.to_excel(writer, 'STI', index=False, columns=header)
writer.save()

You can save multiple sheets in a single excel file.

In [14]:
stockDJIA = excelFile.parse('DJIA')  #first create a dataframe using DJIA stock data for our illustration
stockDJIA

                        Company   Price  Change  % Change      Volume     YTD
0                           NaN     NaN     NaN       NaN         NaN  change
1                        MMM 3M  195.83    0.31    0.0016   1228949.0  -0.168
2          AXP American Express   97.84   -1.16   -0.0117   2041182.0 -0.0148
3                    AAPL Apple  183.92   -3.26   -0.0174  13954806.0  0.0868
4                     BA Boeing  332.93   -3.15   -0.0094   1464360.0  0.1289
5               CAT Caterpillar  133.83   -2.46   -0.0180   1837356.0 -0.1507
6                   CVX Chevron  124.73    0.48    0.0039   3919561.0 -0.0037
7                    CSCO Cisco   42.67   -0.14   -0.0033  13474686.0  0.1141
8                  KO Coca-Cola   43.99    0.24    0.0055   8214329.0 -0.0412
9                    DIS Disney  104.04   -1.29   -0.0122   2406267.0 -0.0323
10           DWDP DowDuPont Inc   65.15   -0.62   -0.0094   3583857.0 -0.0852
11              XOM Exxon Mobil   82.24    0.48    0.0059   7197258.0 -0.0167
12             GS Goldman Sachs  220.38   -2.88   -0.0129   1204376.0  -0.135
13                HD Home Depot  193.62   -0.40   -0.0021   1608418.0  0.0216
14                      IBM IBM  139.57   -0.29   -0.0021   1963232.0 -0.0903
15                   INTC Intel   49.47   -0.73   -0.0145  16327904.0  0.0717
16        JNJ Johnson & Johnson  122.71    1.13    0.0093   4248060.0 -0.1217
17           JPM JPMorgan Chase  103.61   -1.47   -0.0140   8311680.0 -0.0311
18               MCD McDonald's  156.48   -0.39   -0.0025   1437699.0 -0.0909
19                    MRK Merck   60.71    0.25    0.0041   4872655.0  0.0789
20               MSFT Microsoft   99.05   -0.96   -0.0096  14670275.0  0.1579
21                     NKE Nike   76.28   -2.07   -0.0264   5794853.0  0.2195
22                   PFE Pfizer   36.35    0.02    0.0006   9115864.0  0.0036
23          PG Procter & Gamble   77.90   -0.23   -0.0029   5897243.0 -0.1522
24  TRV Travelers Companies Inc  122.77    0.38    0.0031    659117.0 -0.0949
25      UTX United Technologies  124.92   -0.11   -0.0009   2466001.0 -0.0208
26             UNH UnitedHealth  246.98   -0.50   -0.0020   1247991.0  0.1203
27                   VZ Verizon   50.70    0.28    0.0056   8441133.0 -0.0421
28                       V Visa  131.45   -1.05   -0.0079   3621640.0  0.1529
29                 WMT Wal-Mart   84.44    0.44    0.0052   4396238.0 -0.1449
30                 WBA Walgreen   60.76   -0.37   -0.0061   5602311.0 -0.1633

In [16]:
dummy = pd.ExcelWriter('STI_DJIA.xlsx')
stock.to_excel(dummy, 'STI', index=False)
stockDJIA.to_excel(dummy, 'DJIA', index=False)
dummy.save()